project_name: config-registry
before:
  hooks:
    - go mod download
builds:
- id: config-registry
  main: ./cmd/config-registry
  binary: config-registry
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm
    - arm64
    - ppc64le
  goarm: [6, 7]
archives:
- id: config-registry-archive
  name_template: |-
    config-registry_{{ .Tag }}_{{ .Os }}_{{ .Arch -}}
    {{- with .Arm -}}
      {{- if (eq . "6") -}}hf
      {{- else -}}v{{- . -}}
      {{- end -}}
    {{- end -}}
  builds:
    - config-registry
  format_overrides:
    - goos: windows
      format: zip
  files: ["LICENSE"]
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
