apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: config-registry
spec:
  homepage: https://github.com/mumoshu/kubeconf
  shortDescription: Switch between your kubeconfigs
  version: {{ .TagName }}
  description: |
    Also known as "kubeconf", a utility to switch between kubeconfigs stored in your local filesystem.
    Similar to "ctx" and "ns", but for switching the whole kubeconfig.
  caveats: |
    If fzf is installed on your machine, you can interactively choose
    between the entries using the arrow keys, or by fuzzy searching
    as you type.
    See https://github.com/mumoshu/kubeconf for customization and details.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/mumoshu/kubeconf/releases/download/{{ .TagName }}/kubeconf_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubeconf
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/mumoshu/kubeconf/releases/download/{{ .TagName }}/kubeconf_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubeconf
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/mumoshu/kubeconf/releases/download/{{ .TagName }}/kubeconf_{{ .TagName }}_linux_arm64.tar.gz" .TagName }}
    bin: kubeconf
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/mumoshu/kubeconf/releases/download/{{ .TagName }}/kubeconf_{{ .TagName }}_windows_amd64.zip" .TagName }}
    bin: kubeconf.exe
